/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAboutRouteImport } from './routes/_shell.about'
import { Route as ShellContactRouteImport } from './routes/_shell.contact'
import { Route as ShellExperienceRouteImport } from './routes/_shell.experience'
import { Route as ShellProjectsRouteImport } from './routes/_shell.projects'
import { Route as ShellServicesRouteImport } from './routes/_shell.services'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAboutRoute = ShellAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContactRoute = ShellContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExperienceRoute = ShellExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsRoute = ShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServicesRoute = ShellServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/about': typeof ShellAboutRoute
  '/contact': typeof ShellContactRoute
  '/experience': typeof ShellExperienceRoute
  '/projects': typeof ShellProjectsRoute
  '/services': typeof ShellServicesRoute
}
export interface FileRoutesByTo {
  '/about': typeof ShellAboutRoute
  '/contact': typeof ShellContactRoute
  '/experience': typeof ShellExperienceRoute
  '/projects': typeof ShellProjectsRoute
  '/services': typeof ShellServicesRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/about': typeof ShellAboutRoute
  '/_shell/contact': typeof ShellContactRoute
  '/_shell/experience': typeof ShellExperienceRoute
  '/_shell/projects': typeof ShellProjectsRoute
  '/_shell/services': typeof ShellServicesRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/contact' | '/experience' | '/projects' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/experience' | '/projects' | '/services' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/about'
    | '/_shell/contact'
    | '/_shell/experience'
    | '/_shell/projects'
    | '/_shell/services'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/about': {
      id: '/_shell/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ShellAboutRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contact': {
      id: '/_shell/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ShellContactRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/experience': {
      id: '/_shell/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ShellExperienceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects': {
      id: '/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ShellProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/services': {
      id: '/_shell/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ShellServicesRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAboutRoute: typeof ShellAboutRoute
  ShellContactRoute: typeof ShellContactRoute
  ShellExperienceRoute: typeof ShellExperienceRoute
  ShellProjectsRoute: typeof ShellProjectsRoute
  ShellServicesRoute: typeof ShellServicesRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAboutRoute: ShellAboutRoute,
  ShellContactRoute: ShellContactRoute,
  ShellExperienceRoute: ShellExperienceRoute,
  ShellProjectsRoute: ShellProjectsRoute,
  ShellServicesRoute: ShellServicesRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
